# Generated by Django 3.1.7 on 2021-08-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Образовательную программу',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('otch', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Казахский', 'Казахский')], max_length=255, verbose_name='Язык обучения')),
                ('finish_edu', models.TextField(blank=True, null=True, verbose_name='Прежнее место обучение и дата окончания')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('place', models.BooleanField(default=False, verbose_name='Общежитие')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Информация о себе')),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=255, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('born_place', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('national', models.CharField(max_length=255, verbose_name='Нация')),
                ('polojenie', models.CharField(choices=[('Ниже среднего', 'Ниже среднего'), ('Среднее', 'Среднее'), ('Высокое', 'Высокое')], max_length=255, verbose_name='Материальное положение')),
                ('information_parent_mom', models.TextField(blank=True, null=True, verbose_name='ФИО матери, место проживания, номер телефона')),
                ('information_parent_dad', models.TextField(blank=True, null=True, verbose_name='ФИО отца, место проживания, номер телефона')),
                ('created_at', models.DateField(blank=True, null=True)),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='id_card/', verbose_name='Уд.лич лицевая')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='id_card/', verbose_name='Уд.лич обратная')),
                ('diplom', models.FileField(upload_to='diplom/', verbose_name='Диплом')),
                ('zayavka', models.FileField(upload_to='zayavka/', verbose_name='Заявка для приема на учебу')),
                ('fluro', models.FileField(upload_to='fluro/', verbose_name='075-y(флюрография)')),
                ('zdorovie', models.FileField(upload_to='zdorovie/', verbose_name='063-y(Паспорт о здоровье)')),
                ('photo', models.FileField(upload_to='photo/', verbose_name='3x4 фото')),
                ('genereted_file', models.FileField(blank=True, null=True, upload_to='genereted/')),
                ('edu_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.eduprogram', verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
