# Generated by Django 3.1.7 on 2021-08-07 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0001_initial'),
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='edu_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializationapp.specialization', verbose_name='Образовательная программа'),
        ),
    ]
