# Generated by Django 3.1.7 on 2021-03-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_auto_20210321_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='examapp.answer'),
        ),
    ]
