# Generated by Django 3.1.7 on 2021-03-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_auto_20210321_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='examapp.subject', verbose_name='Предмет'),
            preserve_default=False,
        ),
    ]
