# Generated by Django 3.1.7 on 2021-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0006_tasks_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='files',
            field=models.FileField(default=1, upload_to='Files/', verbose_name='Файлы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='files',
            field=models.FileField(default=1, upload_to='Files/', verbose_name='Файлы'),
            preserve_default=False,
        ),
    ]
