# Generated by Django 3.1.7 on 2021-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0007_auto_20210322_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuudentprofile',
            name='subject',
            field=models.ManyToManyField(related_name='student', to='examapp.Subject', verbose_name='Предметы'),
        ),
    ]
