version: '3'

services:
  web:
    build: ./
    command: gunicorn silkwaycollege.wsgi:application --bind 0.0.0.0:8000 --workers=5
    volumes:
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./data/nginx:/etc/nginx/conf.d
      - ./:/usr/src/app
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume: