version: '3'

services:
  web:
    build: ./
    command: gunicorn silkwaycollege.wsgi:application --bind 0.0.0.0:8000 --workers=5
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - wel_known:/usr/src/app/.well-known
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - wel_known:/usr/src/app/.well-known
      - ./certificate:/etc/ssl
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  wel_known: