version: '3'

services:
  web:
    build: ./
    command: gunicorn silkwaycollege.wsgi:application --bind 0.0.0.0:8000 --workers=5
    volumes:
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bakosh21345@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Zz123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  pgadmin-data: