version: '3'

services:
  web:
    build: ./
    command: gunicorn silkwaycollege.wsgi:application --bind 0.0.0.0:8000 --workers=5
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./data/nginx
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
      - ./data/nginx:/etc/nginx/conf.d
      - ./certificate:/etc/ssl
      - ./.well-known/pki-validation/:/usr/src/files/
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  static_volume:
  media_volume:
