version: '3'

services:
  web:
    build: ./
    command: gunicorn silkwaycollege.wsgi:application --bind 0.0.0.0:8000 --workers=5
    volumes:
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./nginx/nginx.conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  static_volume: