# Generated by Django 4.1.3 on 2022-12-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_id_alter_pagecategory_id_alter_widget_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='page',
        ),
        migrations.RemoveField(
            model_name='widgetgalleryphotos',
            name='widgetGalery',
        ),
        migrations.DeleteModel(
            name='WidgetOnlyText',
        ),
        migrations.DeleteModel(
            name='WidgetPhoto',
        ),
        migrations.DeleteModel(
            name='WidgetText',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page.page'),
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.DeleteModel(
            name='WidgetGalery',
        ),
        migrations.DeleteModel(
            name='WidgetGalleryPhotos',
        ),
    ]
