# Generated by Django 4.1.3 on 2022-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_pagetype_delete_pagecategory_remove_page_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка на страницу'),
        ),
    ]
