# Generated by Django 3.1.7 on 2021-05-23 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='abiturent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sapp.abiturent'),
            preserve_default=False,
        ),
    ]
