# Generated by Django 3.1.7 on 2021-04-06 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('uid', models.CharField(max_length=30, verbose_name='Код шифра')),
            ],
            options={
                'verbose_name': '01 Профиль',
                'verbose_name_plural': '01 Профили',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('uid', models.CharField(max_length=30, verbose_name='Код шифра')),
                ('desctiption', models.TextField(verbose_name='Описание')),
                ('desctiption_ru', models.TextField(null=True, verbose_name='Описание')),
                ('desctiption_en', models.TextField(null=True, verbose_name='Описание')),
                ('desctiption_kk', models.TextField(null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialization/', verbose_name='Фото')),
                ('sertification', models.ImageField(blank=True, null=True, upload_to='specializationC/', verbose_name='Фото сертификата')),
                ('duration', models.CharField(max_length=30, verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': '03 Специализация',
                'verbose_name_plural': '03 Специализаций',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('uid', models.CharField(max_length=30, verbose_name='Код шифра')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection', to='specializationapp.section', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': '02 Подпрофиль',
                'verbose_name_plural': '02 Подпрофили',
            },
        ),
        migrations.CreateModel(
            name='SpecializationFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_kk', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_kk', models.TextField(null=True, verbose_name='Ответ')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='specializationapp.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вопрос к специализаций',
                'verbose_name_plural': 'Вопросы к специализаций',
            },
        ),
        migrations.CreateModel(
            name='SpecializationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('visible', models.BooleanField(default=False, verbose_name='Видимость коммента')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комента')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='specializationapp.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Коментарий к специализацию',
                'verbose_name_plural': 'Коментарий к специализаций',
            },
        ),
        migrations.AddField(
            model_name='specialization',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='specializationapp.subsection', verbose_name='подпроифиль'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('uid', models.CharField(max_length=30, verbose_name='Код шифра')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qualification', to='specializationapp.specialization', verbose_name='Специялизация')),
            ],
            options={
                'verbose_name': '04 Квалификация',
                'verbose_name_plural': '04 Квалификаций',
            },
        ),
    ]
