# Generated by Django 3.1.7 on 2021-03-13 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specializationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализаций'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='duration',
            field=models.CharField(default=1, max_length=30, verbose_name='Продолжительность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='sertification',
            field=models.ImageField(blank=True, null=True, upload_to='specializationC/', verbose_name='Фото сертификата'),
        ),
        migrations.CreateModel(
            name='SpecializationFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializationapp.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вопрос к специализаций',
                'verbose_name_plural': 'Вопросы к специализаций',
            },
        ),
        migrations.CreateModel(
            name='SpecializationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('visible', models.BooleanField(default=False, verbose_name='Видимость коммента')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комента')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializationapp.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Коментарий к специализацию',
                'verbose_name_plural': 'Коментарий к специализаций',
            },
        ),
    ]
