# Generated by Django 3.1.7 on 2021-03-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0004_auto_20210314_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('uid', models.CharField(max_length=30, verbose_name='Код шифра')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('uid', models.CharField(max_length=30, verbose_name='Код шифра')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection', to='specializationapp.section', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('uid', models.CharField(max_length=30, verbose_name='Код шифра')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qualification', to='specializationapp.subsection', verbose_name='Специялизация')),
            ],
        ),
        migrations.AddField(
            model_name='specialization',
            name='subsection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='specializationapp.subsection', verbose_name='подпроифиль'),
            preserve_default=False,
        ),
    ]
