# Generated by Django 3.1.7 on 2021-03-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0005_auto_20210330_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qualification', to='specializationapp.specialization', verbose_name='Специялизация'),
        ),
    ]
