# Generated by Django 3.1.7 on 2021-03-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0006_auto_20210330_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='subsection',
        ),
    ]
