# Generated by Django 3.1.7 on 2021-04-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0007_remove_specialization_subsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': '04 Квалификация', 'verbose_name_plural': '04 Квалификаций'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '01 Профиль', 'verbose_name_plural': '01 Профили'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': '03 Специализация', 'verbose_name_plural': '03 Специализаций'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': '02 Подпрофиль', 'verbose_name_plural': '02 Подпрофили'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='subsection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='specializationapp.subsection', verbose_name='подпроифиль'),
            preserve_default=False,
        ),
    ]
