# Generated by Django 3.1.7 on 2021-04-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0009_auto_20210404_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='desctiption_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='specializationfaq',
            name='answer_kk',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='specializationfaq',
            name='question_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
