# Generated by Django 3.1.7 on 2021-03-07 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specializationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Фото')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specializationapp.specialization', verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='government/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False, verbose_name='Чек')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeesapp.employees', verbose_name='Сотрудник которому должен нажаться лайк')),
                ('likeuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь который нажал(а) лайк')),
            ],
        ),
    ]
