# Generated by Django 3.1.7 on 2021-03-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='isimp',
            field=models.BooleanField(default=1, verbose_name='Важность'),
            preserve_default=False,
        ),
    ]
