# Generated by Django 3.1.7 on 2021-03-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0002_government_isimp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Преподаватель колледжа', 'verbose_name_plural': 'Преподаватели колледжа'},
        ),
        migrations.AlterModelOptions(
            name='employeeslikes',
            options={'verbose_name': 'Лайк к преподавателю', 'verbose_name_plural': 'Лайки к преподавателю'},
        ),
        migrations.AlterModelOptions(
            name='government',
            options={'verbose_name': 'Руководство колледжа', 'verbose_name_plural': 'Руководство колледжа'},
        ),
    ]
