# Generated by Django 3.1.7 on 2021-04-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0002_auto_20210406_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='about',
            field=models.TextField(default='Пишите описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='government',
            name='about',
            field=models.TextField(default='Пишите описание', verbose_name='Описание'),
        ),
    ]
