# Generated by Django 3.1.7 on 2021-04-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0003_auto_20210414_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='about_en',
            field=models.TextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='employees',
            name='about_kk',
            field=models.TextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='employees',
            name='about_ru',
            field=models.TextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='government',
            name='about_en',
            field=models.TextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='government',
            name='about_kk',
            field=models.TextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='government',
            name='about_ru',
            field=models.TextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
    ]
