# Generated by Django 3.1.7 on 2021-03-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0004_auto_20210314_1546'),
        ('employeesapp', '0003_auto_20210313_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='specializationapp.specialization', verbose_name='Специализация'),
        ),
    ]
