# Generated by Django 3.1.7 on 2021-04-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializationapp', '0008_auto_20210401_1535'),
        ('employeesapp', '0004_auto_20210325_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='specializationapp.qualification', verbose_name='Квалификация'),
        ),
    ]
