# Generated by Django 3.1.7 on 2021-04-15 09:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0004_auto_20210414_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='about',
            field=ckeditor.fields.RichTextField(default='Пишите описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='about_en',
            field=ckeditor.fields.RichTextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='about_kk',
            field=ckeditor.fields.RichTextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='about_ru',
            field=ckeditor.fields.RichTextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='government',
            name='about',
            field=ckeditor.fields.RichTextField(default='Пишите описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='government',
            name='about_en',
            field=ckeditor.fields.RichTextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='government',
            name='about_kk',
            field=ckeditor.fields.RichTextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='government',
            name='about_ru',
            field=ckeditor.fields.RichTextField(default='Пишите описание', null=True, verbose_name='Описание'),
        ),
    ]
