# Generated by Django 3.1.7 on 2021-09-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0005_auto_20210415_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leсture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeesapp.employees')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекций',
            },
        ),
    ]
