# Generated by Django 4.1.3 on 2022-12-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0006_leсture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeslikes',
            old_name='check',
            new_name='is_check',
        ),
        migrations.AlterField(
            model_name='leсture',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='employeesapp.employees'),
        ),
    ]
