# Generated by Django 3.1.7 on 2021-04-06 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категорий')),
                ('poster', models.ImageField(upload_to='newsC/', verbose_name='Постер')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категорий новости',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок поста')),
                ('description', models.TextField(verbose_name='Описание поста')),
                ('poster', models.ImageField(upload_to='news/', verbose_name='Постер')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newsapp.newscategory', verbose_name='Категория новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False, verbose_name='Чек')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
                ('likeuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь который нажал(а) лайк')),
                ('newspost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.newspost', verbose_name='Пост которому должен нажаться лайк')),
            ],
            options={
                'verbose_name': 'Лайк к новостью',
                'verbose_name_plural': 'Лайки к новостью',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость коммента')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комента')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsapp.newspost', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Коментарий к новостью',
                'verbose_name_plural': 'Коментарий к новостью',
            },
        ),
    ]
