# Generated by Django 3.1.7 on 2021-03-07 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категорий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок поста')),
                ('description', models.TextField(verbose_name='Описание поста')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newsapp.newscategory', verbose_name='Категория новости')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False, verbose_name='Чек')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
                ('likeuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь который нажал(а) лайк')),
                ('newspost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.newspost', verbose_name='Пост которому должен нажаться лайк')),
            ],
        ),
    ]
