# Generated by Django 3.1.7 on 2021-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категорий'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категорий'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категорий'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание поста'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание поста'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание поста'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Загаловок поста'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Загаловок поста'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Загаловок поста'),
        ),
    ]
