# Generated by Django 3.1.7 on 2021-03-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Категория новости', 'verbose_name_plural': 'Категорий новости'},
        ),
        migrations.AlterModelOptions(
            name='newslikes',
            options={'verbose_name': 'Лайк к новостью', 'verbose_name_plural': 'Лайки к новостью'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
