# Generated by Django 3.1.7 on 2021-04-14 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20210406_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Названия')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ютуб')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Постер')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
