# Generated by Django 3.1.7 on 2021-03-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20210313_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='poster',
            field=models.ImageField(default=1, upload_to='newsC/', verbose_name='Постер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='poster',
            field=models.ImageField(default=1, upload_to='news/', verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
