# Generated by Django 3.1.7 on 2021-03-15 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0003_auto_20210314_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость коммента')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комента')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsapp.newspost', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Коментарий к новостью',
                'verbose_name_plural': 'Коментарий к новостью',
            },
        ),
    ]
