# Generated by Django 3.1.7 on 2021-05-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_gallerypost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
    ]
