# Generated by Django 4.1.3 on 2022-12-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20210531_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslikes',
            old_name='check',
            new_name='is_check',
        ),
    ]
