# Generated by Django 4.1.3 on 2022-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_rename_check_newslikes_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='short_description',
            field=models.TextField(default=1, max_length=350, verbose_name='Короткая описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='short_description_en',
            field=models.TextField(max_length=350, null=True, verbose_name='Короткая описание'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='short_description_kk',
            field=models.TextField(max_length=350, null=True, verbose_name='Короткая описание'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='short_description_ru',
            field=models.TextField(max_length=350, null=True, verbose_name='Короткая описание'),
        ),
    ]
