# Generated by Django 4.1.3 on 2022-12-10 14:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_alter_newspost_category_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='files-news/'),
        ),
    ]
